### ISSUE TITLE
libaudit.go errors

### ISSUE THREAD

**Issue by cristiansavaro** [mozilla/audit-go#4] opened 2015-01-27 13:24 UTC
Running the code manually often gives me errors like the one bellow : 

2015/01/26 15:55:35 Acknowledged!!
2015/01/26 15:55:35 NLMSG_ERROR Received..
2015/01/26 15:55:35 Enabled Audit!!
2015/01/26 15:55:35 Acknowledged!!
2015/01/26 15:55:35 Acknowledged!!
2015/01/26 15:55:35 Acknowledged!!
2015/01/26 15:55:35 Set pid successful!!
2015/01/26 15:55:35 Deleting all rules
2015/01/26 15:55:35 NLMSG_ERROR

unexpected fault address 0x0
fatal error: fault
[signal 0xb code=0x80 addr=0x0 pc=0x42b124]

goroutine 16 [running]:
runtime.throw(0x5d20a2)
        /usr/lib/golang/src/pkg/runtime/panic.c:520 +0x69 fp=0x7fbb8870a2e8 sp=0x7fbb8870a2d0
runtime.sigpanic()
        /usr/lib/golang/src/pkg/runtime/os_linux.c:240 +0x13f fp=0x7fbb8870a300 sp=0x7fbb8870a2e8
runtime.memmove(0xc208017190, 0x6f70732f7261762f, 0x13)
        /usr/lib/golang/src/pkg/runtime/memmove_amd64.s:141 +0x214 fp=0x7fbb8870a308 sp=0x7fbb8870a300
_/audit-go/netlinkAudit.(*AuditRuleData).ToWireFormat(0xc208060010, 0x0, 0x0, 0x0)
        /audit-go/netlinkAudit/libaudit.go:96 +0x34d fp=0x7fbb8870a3a8 sp=0x7fbb8870a308
_/audit-go/netlinkAudit.AuditDeleteRuleData(0xc20803e020, 0xc208060010, 0x200000004, 0x0, 0x0)
        /audit-go/netlinkAudit/libaudit.go:732 +0x19c fp=0x7fbb8870a8d0 sp=0x7fbb8870a3a8
_/audit-go/netlinkAudit.DeleteAllRules(0xc20803e020, 0x0, 0x0)
        /audit-go/netlinkAudit/libaudit.go:805 +0xa32 fp=0x7fbb8870aa90 sp=0x7fbb8870a8d0
_/audit-go/netlinkAudit.SetRules(0xc20803e020, 0x0, 0x0)
        /audit-go/netlinkAudit/libaudit.go:866 +0x4a7 fp=0x7fbb8870ae70 sp=0x7fbb8870aa90
main.main()
        /audit-go/main.go:53 +0x867 fp=0x7fbb8870af50 sp=0x7fbb8870ae70
runtime.main()
        /usr/lib/golang/src/pkg/runtime/proc.c:247 +0x11a fp=0x7fbb8870afa8 sp=0x7fbb8870af50
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445 fp=0x7fbb8870afb0 sp=0x7fbb8870afa8
created by _rt0_go
        /usr/lib/golang/src/pkg/runtime/asm_amd64.s:97 +0x120

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        /usr/lib/golang/src/pkg/runtime/mheap.c:507
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445
exit status 2

**Comment by AALEKH** [comment] 2015-01-27 14:07
Hi @cristiansavaro , thanks for raising the issue, can you please share with us the architecture of your machine ? This will help us resolve the issue.

**Comment by cristiansavaro** [comment] 2015-01-27 15:33
[root@oel6 ~]# uname -a
Linux oel6 3.8.13-55.el6uek.x86_64 #2 SMP Mon Dec 1 11:32:40 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cristiansavaro** [comment] 2015-01-27 15:37
audit-2.4.1-1.el6.x86_64

**Comment by cosminilie** [comment] 2015-03-03 12:17
@AALEKH any updates on this issue?

**Comment by AALEKH** [comment] 2015-03-03 12:58
Hi @cosminilie , @cristiansavaro , we were trying to make some major change with the library, but nevertheless this issue will end by this week. Sorry for any inconvenience caused !!

**Comment by cosminilie** [comment] 2015-03-09 07:14
@AALEKH  and team, thanks a lot for the great work!!

**Comment by AALEKH** [comment] 2015-03-14 10:30
Hi @cosminilie , many of us are busy with some Internship/ Academic Programmes , which  is causing delay in addressing the issue, however we will try our our best to complete the issue ASAP.

**Comment by cosminilie** [comment] 2015-03-17 12:08
@AALEKH Thanks a lot of the update, really appreciate it.

**Comment by cosminilie** [comment] 2015-04-27 11:43
Hi, any updates on how things are moving along?

**Comment by alexjhart** [comment] 2015-09-15 17:32
Hello. Any updates?

**Comment by hxjuneja** [comment] 2015-11-16 00:34
Seems like we have a race condition here.
Since I am not able to reproduce this on my system, Can anyone of you please post output of 
`go run -race main.go` ?

**Comment by cristiansavaro** [comment] 2015-11-16 09:45
Here it is : 

2015/11/16 11:44:14 Acknowledged!!
2015/11/16 11:44:14 NLMSG_ERROR Received..
2015/11/16 11:44:14 Enabled Audit!!
2015/11/16 11:44:14 Acknowledged!!
2015/11/16 11:44:14 Acknowledged!!
2015/11/16 11:44:14 Acknowledged!!
2015/11/16 11:44:14 Set pid successful!!
2015/11/16 11:44:14 Deleting all rules
2015/11/16 11:44:14 NLMSG_ERROR

2015/11/16 11:44:14 Deleting Done!
2015/11/16 11:44:14 actions are :  always
2015/11/16 11:44:14 fields are map[name:path op:eq value:/bin/ls]
2015/11/16 11:44:15 fields are map[op:eq value:x name:perm]
2015/11/16 11:44:15 setting syscall rule rmdir
2015/11/16 11:44:15 Going for arch
2015/11/16 11:44:15 Going for key
2015/11/16 11:44:15 setting syscall rule mkdir
2015/11/16 11:44:15 Going for arch
2015/11/16 11:44:15 Ack
2015/11/16 11:44:15 Ack
2015/11/16 11:44:15 type=CONFIG_CHANGE msg=audit(1447667055.000:15444): auid=0 ses=2413 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op="add rule" key="rmd" list=4 res=1

2015/11/16 11:44:15 type=CONFIG_CHANGE msg=audit(1447667055.001:15445): auid=0 ses=2413 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op="add rule" key=(null) list=4 res=1

# 

WARNING: DATA RACE
Write by main goroutine:
  os.(_file).close()
      /usr/lib/golang/src/os/file_unix.go:109 +0x1d7
  os.(_File).Close()
      /usr/lib/golang/src/os/file_unix.go:98 +0x91
  main.main()
      /audit-go/main.go:88 +0x1245

Previous read by goroutine 5:
  os.(_File).write()
      /usr/lib/golang/src/os/file_unix.go:212 +0xc4
  os.(_File).Write()
      /usr/lib/golang/src/os/file.go:139 +0xc3
  os.(*File).WriteString()
      /usr/lib/golang/src/os/file.go:199 +0xc6
  main.func·001()
      /audit-go/main.go:71 +0x296

Goroutine 5 (running) created at:
  main.main()

#       /audit-go/main.go:79 +0x119f

Found 1 data race(s)
exit status 66

**Comment by hxjuneja** [comment] 2015-11-19 21:31
@cristiansavaro  can you git pull  and test again?

**Comment by cristiansavaro** [comment] 2015-11-20 06:39
i've done that also.
i still get some NLMSG_ERROR messages but it seems to be working.
here's the output now:

2015/11/20 08:34:38 Acknowledged!!
2015/11/20 08:34:38 NLMSG_ERROR Received..
2015/11/20 08:34:38 Enabled Audit!!
2015/11/20 08:34:38 Acknowledged!!
2015/11/20 08:34:38 Acknowledged!!
2015/11/20 08:34:38 Acknowledged!!
2015/11/20 08:34:38 Set pid successful!!
2015/11/20 08:34:38 Deleting all rules
2015/11/20 08:34:38 NLMSG_ERROR

2015/11/20 08:34:38 Deleting Done!
2015/11/20 08:34:38 fields are map[name:path op:eq value:/bin/ls]
2015/11/20 08:34:38 fields are map[value:x name:perm op:eq]
2015/11/20 08:34:38 actions are :  always
2015/11/20 08:34:38 setting syscall rule rmdir
2015/11/20 08:34:38 Going for arch
2015/11/20 08:34:38 Going for key
2015/11/20 08:34:38 setting syscall rule mkdir
2015/11/20 08:34:38 Going for arch
2015/11/20 08:34:38 NLMSG_ERROR
2015/11/20 08:34:38 type=CONFIG_CHANGE msg=audit(1448001278.521:19917): auid=0 ses=3079 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op="remove rule" key="" list=4 res=0

2015/11/20 08:34:38 Ack
2015/11/20 08:34:38 NLMSG_ERROR
2015/11/20 08:34:38 type=CONFIG_CHANGE msg=audit(1448001278.521:19918): auid=0 ses=3079 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op="remove rule" key=(null) list=4 res=1

2015/11/20 08:34:38 type=CONFIG_CHANGE msg=audit(1448001278.528:19919): auid=0 ses=3079 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op="add rule" key="rmd" list=4 res=0

2015/11/20 08:34:38 Ack
2015/11/20 08:34:38 type=CONFIG_CHANGE msg=audit(1448001278.529:19920): auid=0 ses=3079 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op="add rule" key=(null) list=4 res=1

**Comment by cristiansavaro** [comment] 2015-11-20 06:48
After a while leaving it run i also got these:

2015/11/20 08:40:01 Unknown:  1101
2015/11/20 08:40:01 Unknown:  1103
2015/11/20 08:40:01 Unknown:  1006
2015/11/20 08:40:01 Unknown:  1105
2015/11/20 08:40:01 Unknown:  1104
2015/11/20 08:40:01 Unknown:  1106

**Comment by hxjuneja** [comment] 2015-11-20 10:06
@cristiansavaro Note that NLMSG_ERROR is not always an error when first 4 bytes of data are zero they represent acknowledgment from kernel. We emitted this for debugging purposes. We will fix this as library matures.

Also, regarding Unknown, currently we don't support all 'Types' so we just emit unknown for type which are not known. This will be fixed soon.

closing this issue.

**Closed as completed by hxjuneja** 2015-11-20 10:06 UTC

**Comment by hxjuneja** [comment] 2015-11-28 11:51
@cristiansavaro just added support for all message types should work now.
please pull and test

**Comment by cristiansavaro** [comment] 2015-11-28 13:26
here's the result now : 

>  go run -race ./main.go
> 2015/12/16 14:04:14 Acknowledged!!
> 2015/12/16 14:04:14 NLMSG_ERROR Received..
> 2015/12/16 14:04:14 Error while fetching status!
> exit status 1

PS : i pulled from master as issue #7 was merged.
